#ifndef DEFINES_H
#define DEFINES_H

#define MAX_TEXTURE_COUT 32
#define MAX_MATERIAL_COUNT 32
#define MAX_MESHES_COUNT 256

enum MeshIndex {
    MESH_EMPTY = 0,
    MESH_BOX,
    MESH_BACKPACK,

    MESH_COUNT,
};

//NOTE(tomi):Game textures
enum TextureIndex {
    TEXTURE_EMPTY = 0,
    TEXTURE_CUBE,
    TEXTURE_BOX,
    TEXTURE_WOODBOX,
    TEXTURE_WOODBOX_SPECULAR,
    TEXTURE_BACKPACK_DIFUSE,
    TEXTURE_BACKPACK_SPECULAR,

    TEXTURE_COUNT,
};

//NOTE(tomi):Game Materials
enum MaterialIndex{
    MATERIAL_EMPTY= 0,
    MATERIAL_TEST,
    MATERIAL_BACKPACK,

    MATERIAL_COUNT,
};

#endif
